### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by Martin-Andersen** [thinkloop/knockout-js-infinite-scroll#1]
Nice add on to KO. Do U have an example where U don't pull all the items at once? Like U would do with normal paging.

**Comment by thinkloop** [comment]
Thanks Martin. I updated the fiddle to load 100 new items when you reach the end of the viewport:

// add more items if scroll reaches the last 100 items
if (self.filteredItems.peek().length - self.filteredItems.infinitescroll.lastVisibleIndex.peek() <= 100) {
  populateItems(100);
}

http://jsfiddle.net/thinkloop/7MqJ2/

**Comment by Martin-Andersen** [comment]
OK that was easy, Thank's
