### ISSUE TITLE
Underscore.js dependency

### ISSUE THREAD

**Issue by pimschaaf** [thinkloop/knockout-js-infinite-scroll#11]
The "simplest implementation of this component" includes underscore.js as a dependency. Is this really required/why is it included?

Thanks!

**Comment by thinkloop** [comment]
I seem to have missed this till now. 

This lib is dependency-free, where do you see underscore?

**Comment by rohithnair** [comment]
if you look at the jsfiddle provided in the main page, it has underscore.js as a dependency.

So I tried removing underscore and error occured at  _.debounce(function() {}.

 ![Undescore dependency](https://cloud.githubusercontent.com/assets/1162041/12953255/7f8d5d22-d011-11e5-9f97-990fcc0df629.png)

**Comment by pimschaaf** [comment]
Thanks for that @rohithnair. I couldn't quite recall where I got the quote from - still can't, still think it must be in the history of the readme.md, but can't find it there either.

Valid question becomes why underscore.js is in the fiddle; +1.

**Comment by rohithnair** [comment]
Actually it is in the html file you showed in the jsfiddle ,nothing to do with the library though.

**Comment by thinkloop** [comment]
Thanks for finding it.

In practice it is likely that debouncing will be needed, so I thought I'd show it in the fiddle. Now that you bring it up tho, it could be seen as an unnecessary complexity, so I removed it.

Best,
Baz
