### ISSUE TITLE
Question: Combine infinite scroll with filter/search?

### ISSUE THREAD

**Issue by danielabar** [thinkloop/knockout-js-infinite-scroll#12]
Is it possible to combine infinite scroll with knockout filter/search?

I'm using the approach [explained here](http://www.knockmeout.net/2011/04/utility-functions-in-knockoutjs.html) to filter a list based on user typing into a search box. 

The problem is the list (data items retrieved from server) is growing. Currently ~230 items, and it's getting slow. So I put infinite scroll in place which speeds things up, but now not sure how to also filter the list.

**Comment by thinkloop** [comment]
Hi! 

I wonder if what you need is infinite scroll, have you seen this: 
    https://github.com/thinkloop/knockout-js-progressive-filter

Example fiddle: 
    http://jsfiddle.net/thinkloop/Mkg72/

Let me know. If that doesn't work for you we can certainly filter infinite-scroll.

**Comment by danielabar** [comment]
I'll take a look at progressive filter. Thanks for quick reply!
