### ISSUE TITLE
Items change before bottom of the page is reached

### ISSUE THREAD

**Issue by Skeldave** [thinkloop/knockout-js-infinite-scroll#14]
Hi,

I'm trying to implement this but I can't get the items to change when they are off the page, they change after a small scroll (Or 2 wheel turns on a mouse), making all the items change in the visible area, rather than when hidden.

These are the values.
firstVisibleIndex - 0
lastVisibleIndex - 23
totalItems = 434

24 items can fit in the visible area of the page.

I think it might be something to do with my updateViewportDimensions. 

```
function updateViewportDimensions() {

   var itemsWidth = $(".tab-content").outerWidth(),
        itemsHeight = $(".tab-content").outerHeight(),
        itemWidth = $('.keyword-container').first().outerWidth(),
        itemHeight = $('.keyword-container').first().outerHeight();

    self.MasterList.infinitescroll.viewportWidth(itemsWidth);
    self.MasterList.infinitescroll.viewportHeight(itemsHeight);
    self.MasterList.infinitescroll.itemWidth(itemWidth);
    self.MasterList.infinitescroll.itemHeight(itemHeight);
}

 $(".tab-content").scroll(function () {
    self.MasterList.infinitescroll.scrollY($(".tab-content").scrollTop());
});

$(window).resize(function () {
    updateViewportDimensions();
});
```

EDIT1: The increments now work properly but I'm still having the issue of the items refreshing before they are off the screen. 

It happens when I get to firstVisible: 30, lastVisible: 53 and every subsequent scroll after this point.

EDIT2: I also have another problem, it only displays the first 117 items in the list, rather than the full 434

Thanks for any help.

**Comment by thinkloop** [comment]
Hello,

It's tough to debug these issues without seeing all the code. I wonder if it has to do with the sizing of the elements:
- are they all the same size?
- do the specified sizes (`console.log`) match the actual sizes of the elements (see with inspector)?

**Comment by Skeldave** [comment]
Hello,

I think I have posted everything which relates to the infiniteScroll. Everything else is just standard knockout. Do you have any specific parts you want me to post?

The elements are in a bootstrap grid, so variable width but they have a fixed height of 194px.

```
var itemsWidth = $(".tab-content").outerWidth(), //The scrollable parent container width
itemsHeight = $(".tab-content").outerHeight(), //The scrollable parent container
itemWidth = $('.keyword-container').first().outerWidth(), //The first element in the bootstrap grid 
itemHeight = $('.keyword-container').first().outerHeight(); //
```

The following is logged from the console:

itemsWidth: 1920px
itemsHeight: 764px
itemWidth: 312px
itemHeight: 194px

The following are the inspected values

itemsWidth: 1920px
itemsHeight: 764px 
itemWidth: 312.156px
itemHeight: 194px

I noticed that in JSFiddle example provided, it shows the following:

container w/h: 240px / 300px 
each item w/h: 220px / 20px

When I inspect the elements I actually see the following results:

container w/h: 415px (plus 40px padding) / 329px 
each item w/h: 415px / 20px

http://jsfiddle.net/thinkloop/7MqJ2/

Could you explain why this is? Thanks.

**Comment by Skeldave** [comment]
I managed to solve the issue, it was my mistake. Thanks anyway!
