### ISSUE TITLE
JS Fiddle Demo clarification

### ISSUE THREAD

**Issue by Puyo95** [thinkloop/knockout-js-infinite-scroll#7]
In your JS FIddle demo using your library you have the following lines of code.

```
// detect scroll
$(items).scroll(function() {
    self.filteredItems.infinitescroll.scrollY($(items).scrollTop());
```

The lines of code above suggests that there is a variable called "items." I fail to find where in any of your code this variable is being set. Somehow the "items" property is being set to the list of "<li>" DOM elements that is returned by "$('#items')" but I fail to see the declaration "var items" or the setter "items = $('#items')" anywhere in your code. There is also a property in the view model called "items" that seems to be unused in the code. I am having a hard time understanding how to use this library because of these discrepancies. I also feel that the responsibility of updating the viewport dimensions should be given to the library itself, not the user of the library; this would make it easier to use.

**Comment by thinkloop** [comment]
Hey Puyo95,

Using "items" like I did is mis-leading and bad form, thanks for catching it - I updated the fiddle to more explicitly reference the UL element with id "items" - actually I changed it itemsUL. If you go to any site, find any element with an id, then do console.log(the_id) you will reference that element.

With regards to auto-calculating the view dimensions, there are several reasons I didn't include them in the component itself. One is flexibility. Doing it like this let's you do cool things like having the main browser scroller scroll a sub-element with various offsets, or change layout from tile to horizontal to vertical without changing items, or debouncing scroll events, or assigning custom measurements to items, or including/excluding different paddings/margins in calculations, etc. 

Another reason is that it is very expensive. Introspecting the dom is the 2nd most costly thing you can do after updating the dom. If the app needed those dimensions elsewhere, it would be bad to introspect them multiple times. Interactions with the dom should be shared with the rest of the app as much as possible.

Does that make sense? If there's any other help you need don't hesitate to ask. 

BTW are you able to close the ticket? If so can you do so if you don't have follow-up questions?

**Comment by Puyo95** [comment]
Thank you for your response. I can see you fixed the fiddle; that magic variable was driving me nuts. Yes, you make a lot of sense. Now I understand why you delegate the view dimensions. 

I will post more questions if I need to. Closing ticket.

**Comment by Puyo95** [comment]
Actually I have to re-open this. Earlier I mentioned the items property for the view model  that is set to an Observable array; I don't see this property being used anywhere.

**Comment by thinkloop** [comment]
You are right! Originally I wanted to show infinite scroll on filtered items but decided it was an unnecessary complexity. Removed from fiddle.
