### ISSUE TITLE
Internet Explorer 11 compatibility

### ISSUE THREAD

**Issue by Puyo95** [thinkloop/knockout-js-infinite-scroll#8]
The JS Fiddle demo does not work under IE 11 unless your in 'IE 10' compatibility mode.

**Comment by Puyo95** [comment]
Setting the jQuery version to latest allows the user to see the list of items but scrolling is very buggy.

**Comment by thinkloop** [comment]
Hmmm, this was tested in IE, I think it may have been 10 tho, thanks for letting me know, looking into it.

**Comment by thinkloop** [comment]
If you disable smooth scrolling in "internet options" > "advanced" > "use smooth scrolling" (uncheck), it starts working like other browsers - still looking for a work-around without that of course.

**Comment by thinkloop** [comment]
It seems there are a bunch of problems with IE11 and smooth scroll around the web. If you check out pintrest, even their infinite scroll is choppy in IE11.

I did resolve the issue tho by applying a debounce to the scroll detection. It makes it look smooth again, and anyway, in the vast majority of real-world cases you would want to debounce scroll detection. I updated the fiddle, let me know what you think.

(please close this ticket if you are able to and have no follow-up)

**Comment by Puyo95** [comment]
I noticed that your latest changes makes the scroll bar be less responsive on FireFox. I used to be able to drag the handle downward smoothly now it jumps and is choppy; not sure if this is what you intended. My Windows 8.1/IE11 Desktop Version is still not working even with smooth scrolling turned off; still works with IE10 mode. I wonder if Modernizr can help us with this issue.

**Comment by thinkloop** [comment]
I wonder if there is a proper solution besides conditionally applying debounce depending on the browser. I don't think modernizer will help, but I'll take a look. The way it is now is already smoother than pintrest in all browsers - try using the handle on pintrest and see as you get to the bottom. 

I'm on Win8.1 too, and when I remove smooth scrolling, then use the mouse-wheel or arrows on the scrollbar (not the handle), the scrolling is a lot more similar to the other browsers without the jumping up and down - not you?

I think dragging the handle and infinite scroll are generally incompatible - do u know of an example where dragging the handle works very nice with infinite scroll?
