### ISSUE TITLE
infinite scrolling with variable height

### ISSUE THREAD

**Issue by z4711** [thinkloop/knockout-js-infinite-scroll#9]
Hello, i'm searching for an infinite scrolling component for my single page application (Durandal)

![capturex](https://cloud.githubusercontent.com/assets/6848525/3859202/c127da68-1f15-11e4-93f5-bf8f97455cbf.PNG)
![capturey](https://cloud.githubusercontent.com/assets/6848525/3859208/c8815ea6-1f15-11e4-9580-4aaf5c18526a.PNG)

at the moment there is a simple pagination, but i'm not happy with it.

remark:
- i'm using Bootstrap 3 (mobile first approach)
- only 1 item per row (fix)
- item height can vary, depending of his contents and viewport (window width)
- data acquisition is ajax driven, webapi interface on server side (can be modified/extended for any needs)
- the totalItems.Count is known by the server, available on client
- additionally i would like to provide a way to jump to a certain region, may be something like a slider (HTML5 input type: range)
- i also would like to provide Ctrl-End, Ctrl-Home functionallity (jump to start/end of list) 

there is app show case under: http://31.165.164.194/stm
please select some artists first (to build a big list), then click playlist

i would be glad to get some tips and hints before i start with knockout-js-infinite-scroll

regards Peter

**Comment by thinkloop** [comment]
Hey Peter, cool site!

The fiddle linked in the docs solves the case for a single column list, so might be a good place to start: http://jsfiddle.net/thinkloop/7MqJ2/

However you mentioned that your items have a variable height, while this component is optimized to work with fixed heights for items. In the fiddle, see the updateViewportDimensions() function that runs whenever the viewport changes size to update all the relevant sizes. If you add variable height support I could merge it in.

Best,
Baz

**Comment by z4711** [comment]
Hey Baz
Yes i saw the fiddle, i think i will start from there...

I definitely will take your approach of conditional rendering, thats a
great idea (knockout becomes very slow with big lists).

From my understanding the self.items (view model) will grow up (infinitely)
when the user scrolls down.
In my app that will also be a problem when we are running on very poor
devices (iPod, etc).

I'm thinking about something like: "holding only a certain amount of items
around a virtual cursor"
I've still not really started with it, but knockout-js-infinite-scroll will
definitely stand beside when i go for...

Many many years ago, i was handling very big lists in a Delphi win32 app, i
remember to "Orpheus Virtual Listbox".
It was a great approach at time, what we are trying now, is a kind of
similar.

Regards Peter

2014-08-12 0:26 GMT+02:00 Baz notifications@github.com:

**Comment by thinkloop** [comment]
> From my understanding the self.items (view model) will grow up (infinitely)
> when the user scrolls down. In my app that will also be a problem when we are running on very poor
> devices (iPod, etc).

I wonder if that will be the case if you empty the contents of items that are not in view so that only the outer container remains to maintain structure. Devices can generally handle hundreds of thousands of super-simple empty containers. Will need testing tho, of course, and you may have to end up replacing all containers out of view, with a single container that expands in height as more items scroll out of view. Let me know how it goes!

**Comment by z4711** [comment]
Hello Baz

tomorrow i'll try to integrate infinite scroll into my Playlist (see pic).
as you can see the items are not of equal high, some songs have more infos,
others have less
i will give it a try, specifying the minimal high and then see what's
happen.

remembering your comment about holding tousends of item, it try it out:
with Soundstree [http://84.226.142.49/stm] it's very easy to select some
tousand's of songs and build a playlist from.
you are right, transfering some tousand items, holding them in a viewmodel
isn't the case at all (all that is done in a couple of ms),
the bottleneck is Knockout (only Knockout)

remark: my app is based on Durandal, that also implies an AMD loader
(require.js), i love this plattform but that also gives me some limitations
how to implement things.

i cannot understand why 'conditional rendering' isn't more popular

regards Peter

2014-08-14 3:11 GMT+02:00 Baz notifications@github.com:

**Comment by z4711** [comment]
Hi Baz

after some studies, i have a few questions:
1. why making a copy (displayItems) of the target items?
   why not use a something like
              <ul id="itemsUL" data-bind="foreach: items">
   
   
   
   ```
                   <li>
   ```
   
   contents
                       </li>
   
   
   
   ```
          </ul>
   ```
   
   and forcing rerending, e.g.target.valueHasMutated() when the related
   indexes has changed
2. is there a certain reason for rendering all li-tags? in your sample the
   li-tags are outside the conditional rendering (<!-- ko if: )
3. heightBefore and heightAfter (internally they are not used) are for what?

best regards Peter

2014-10-01 23:44 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by thinkloop** [comment]
Hi Peter,

Great questions!
1. The reasons are mainly performance related. The way that function makes a nice, small "displayItems" object, from a potentially huge "items" object, is much faster than the way ko would do it. Additionally, it gives more control when items are rendered. For example, let's say items are updated one-by-one by your service, but you only want to render them when they are all updated so the ui doesn't thrash around - this gives you control of when to render your final display list. Additionally there is a check for similarity in there that stops the items from re-rendering in case the resulting set is the same (whereas it would have re-rendered anyway otherwise). This all comes back to the fact that raw javascript is infinitely faster than any dom manipulation, so adding any sort of javascript to reduce dom manipulation, is, in general, a big win. Also I was going to make the property overrideable so people could put their own logic in there to render the final set how they want, but I never got around to that :)
2. When I built this, I was using a tile-layout by inline-block'ing all the items. Items would continue horizontally until the end of the line, then start at the next line. If the browser was resized, items would jump around to different rows and columns, rightly so. I didn't want to rebuild the whole browser layout system to know where each element was at a given time, so instead I let the browser do what it needs to, but hide all unnecessary complexity so that it remains as efficient as possible. If your layout is simpler or linear you may be able to do it a bit differently. 
3. This is actually related to #2. At one point I wanted to give the ability to not have to render all the empty containers, and instead render one huge component out of view that takes up the place of all the empty containers. These properties help in that direction, and could perhaps be used in a different kind of implementation. I did not test them too much tho.

All the best!

**Comment by z4711** [comment]
Hi Baz

Great answer, thank you very much
this infos helps a lot

will (2) also work with Twitter Bootstrap 3 grid system? i'm curios

infinite-scroll should probably also be applied to the following page:
http://84.226.142.49/stm#bgcat/512/3502105529 , there are already more than
500 items (it's slow) and there will be more items in the future (resize
the browser window to tablet or phone size). On this page a kind of
incremental rendering on scroll (demand) could be handy, "incremental
binding/rendering with knockout, i haven't seen that for now (at least not
with Durandal, ko.applyBindings is called by Durandal!)"

another place is the full text search result(s):
http://84.226.142.49/stm#srchRes/0/0?arg=gon*&opt=575&vm=3&sm=1&dc=false&pn=1
, the existing paging could be removed

thanks for your help,
best regards Peter

2014-10-05 0:32 GMT+02:00 Baz notifications@github.com:

**Comment by z4711** [comment]
Hi Baz

the playlist is now with infinite scoll...
http://84.226.142.49/stm#bgcat/512/1038821385
select all of Billy Cobham, Chick Corea and Dave Matthews, then you should
have about 2612 songs selected. In the main menu click to "Playlist" then
you are there...

First i tried rendering from the original items with conditional rendering,
like
   

as result i had a big confusion, after recalculating the indices as result
of scroll operation, another scroll happens due to the fact other items has
been rendered... finally it was unusable at all. Also on first render,
knockout is doing something with all items, ignoring the  
            <tr class="sct-target" data-bind="attr: { id: 't' + $index() }">
            .....
does result into knockout bindings errors
i had to change it into (using tbody), then it works as expected

```
<table id="playLst-data" class="table table-condensed borderless">
    <tbody data-bind="foreach: displayTracks()">
        <!-- ko if: $index() >= $root.firstHiddenIndex -->
        <tr class="sct-target" data-bind="attr: { id: 't' + $index() }">
        .....
```

ok the main interesting point is, how to make it responsive and able to
handle variable high items?
also for other reasons, all items are marked with "sct-target" class and a
unique id which in fact is the item index (as you see above), so without
big effort i can determine the first (topLeft) and the last (bottomRight)
visible item...

```
    evalFirstLastVisible: function (section, scrollTop) {
        var st = scrollTop || $(window).scrollTop();
        var topLim = st + $(".navbar-header").height();
        var botLim = st + $(window).height() -
```

$(".navbar-fixed-bottom").height();

```
        var result = {};
        var pos;
        var id;
        $(section + ' .sct-target').each(function () {
            pos = $(this).offset().top;
            id = $(this).attr('id');
            if (pos > topLim && !result.topLeft) {
                result.topLeft = id; // first entire visible top-left
```

item
                } else if (result.btmRight && pos > botLim) {
                    return false;   // first not visible item
                }
                result.btmRight = id;
            });
            return result;
        },

for the rest i included viewmodel and view, please search for
'updateScope', ... it's quick and dirty,
a specific/discret implementation, not as modular as your
knockout-js-infinite-scroll, but it does the job
(remark: scrollHandler is already debounced).

two things i'm wondering:
1. after replacing displayItems, there is no scroll even we have more or
less items in the 'firstHiddenIndex area' (that is nice, but i don't
understand why)
1. the 'Home' key works as expected, pressing Home goes to Index 0, the
   start of list (that is nice, but i don't understand why)

conclusion:
it's pretty nice

to do:
i would also like to have the 'End' button working, going to the end of list
i need the feed to certain item in the list (show playing track)
a smart calculation instead the hard coded amount of padding items (for a
more generic implementation)

thanks for your help,
best regards Peter

2014-10-05 21:19 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by z4711** [comment]
after testing it with a very poor/slow android tablet i'am not so shure
about the 'no scroll after scroll'

scrolling big playlist on tablets and probably phones too, is not working
very well, it's a kind of timing problem i guess

i have to investigate this issue

regards Peter

2014-10-07 11:15 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by z4711** [comment]
i made some console log messages for testing, they are redirected to the
server log (so you can see them too: Main menu -> Hi... -> Serverlog); open
one instance on a PC (ServerLog), another with your phone or tablet (for
scrolling in playlist)...

Base address: http://84.226.142.49/stm

i couldn't see anything special in the log (no repeated updateScope calls
per scroll activity),
but regardless the playlist on my tablet is jumping around...

2014-10-07 12:03 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by z4711** [comment]
Hi Baz
it seems i need your help...

after successfully implementing continous scrolling for my playlist i tried
to implement a kind of goto, showing the song actually playing
that means instead of starting with item at index 0, i would like to start
with index xxx, as first showing a part anywhere in the list.
it wasn't really complicated to realize that, but then cames the bad
surprise...

after starting somewhere in the middle, i can scroll forward to the end of
list as expected, but after scrolling back (upward) a few times my playlist
is on scrolltop = 0, but it's not showing Item 0. Strange, it seems i dont
have enough scroll range to go to start of list.

Any idea, your answer 3? is that the direction? how i can achive something
like without fixed row high?

i would be glad if you have any idea what to do

regards Peter

2014-10-07 14:19 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by thinkloop** [comment]
Hey Peter,

I'm glad you've successfully got it up and running in various places! 

With regards to the "goto" are you trimming your collection to start at the active item? Would it be better instead to scroll to that item so that it is on screen rather than trim the underlying collection?

Best,
Baz

**Comment by z4711** [comment]
Hey Baz
thanks for quick respond

yes you are right, but we need both:
first ensure that the item is between first and lastHidenIndex, rendering
the related items
then scrollto the item actually playing

it seems, when we start normally (at item 0), then scroll downto any
region, the browser keep the positions in a correct way, the scroll range
is continuously expanded, but when i start rendering somewhere in the
middle it does not.

assuming we have a total of 1000 songs, the song at index 500 is actually
playing - when we open the playlist the songs at indices 480...520 are
rendered, scrolling to item 500 is initiated. All that works like e
charme... When we start to scroll upwards, after same page up's the problem
arrives, the browser scroll's to top (0), but we are not at the start of
the list.

can you check that with your solution, e. g. start browsing in the middle
(centered to item 250), then you go and scroll upwards?
please

regards Peter

2014-10-09 3:49 GMT+02:00 Baz notifications@github.com:

**Comment by thinkloop** [comment]
You are doing some advanced stuff Peter! You should blog about it afterwards.

If you can make a simplified fiddle that demonstrate the issue, I would be happy to take a look.

Best,
Baz

**Comment by thinkloop** [comment]
You can fork mine: http://jsfiddle.net/thinkloop/7MqJ2/

**Comment by z4711** [comment]
Hi Baz

i made a small test page, derived from your fiddle
it includes variable height items and also starts scrolling from somewhere
i didn't put it on fiddle, because it's not really
using knockout-js-infinite-scroll

feel free take some ideas and use them further in
knockout-js-infinite-scroll,
tell me what you think,

best regards

Peter

2014-10-09 4:37 GMT+02:00 Baz notifications@github.com:

**Comment by z4711** [comment]
Hi Baz

i changed the #items to 10'000
i implemented a goto index functionality
some additional console message are available
i made some tests, goto 9999 resp. goto 0 when we are at the end of the list

conclusion: up to 1000 items it looks pretty well, for more than 5000 it's
not usable

try it yourself, any ideas are welcome

regards Peter

2014-10-15 11:16 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by z4711** [comment]
the last version is with variable but still known height, the height of the
pre-rendered <li>-tags is known...

the reality will be worse, the contents of each surrounding tag (<li> in
the sample, in my app it will be <tr>) will be determined by the contents,
it's not known at pre-render time. as result of that the visible items will
jump around, when the hidden items are updated.

2014-10-16 17:30 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by thinkloop** [comment]
Hey Peter,

I haven't forgotten about you! :) But I also haven't had a chance to take a look at what you provided so far, I've been swamped with some projects here. Hopefully I can dig in within the next few days or week. I hope it isn't blocking you, and that you are figuring out ways around the issues. If you do find solutions, please post them here for others to see.

Best,
Baz

**Comment by z4711** [comment]
hi Baz
1. ko-scroll-docstruct-maintained
   is a kind of similar to your original component, all items are
   pre-rendered (empty contents)
   
   advantage:
        items with variable height,
        document structure is maintained (one or more columns)
        starting from any position, scroll from the middle to start or to
   end
   disadvantage:
        the height of each item must be known in advance
        max items may be 2000 or 3000
2. ko-scroll-pure-virtual
   is a different approach (pure virtual), only rendered whats visible
   with a certain reserve before and behind
   
   advantage:
        item height can be determined by it's contents (height is not
   needed in advance),
        any number of items can be showed
        starting from any position, scroll from the middle to start or to
   end
   disadvantage:
        document structure is not maintained (only for single column),
        it's tricky to distinguish between real scroll events and those
   caused by re-rendering, re-positioning

further work:
how to make it more generic, making a component?
there are some constants: min padding = 20, debounce times for scroll,
isrendering

try it out, let me know what you think

best regards, Peter

2014-10-18 5:53 GMT+02:00 Baz notifications@github.com:

**Comment by z4711** [comment]
hi Baz

for the moment that will be my final release...

there is no need for ignoring/suppressing scroll events (self.isRendering
in the version before),
the treshold in the calculation of items to be rendered does the job.
i also removed the id's from user data, they can easely be generated on the
fly.

regards Peter

2014-10-20 15:16 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by z4711** [comment]
do you have an idea how to hide the scrollbar from itemsUL and establish a
'faked' one which is proportional to the 500000 items resp. to the part
actually showed? it must be something with a small footprint; i was looking
for malihu-custom-scrollbar, but that's an overkill i think

regards Peter

2014-10-20 22:57 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by thinkloop** [comment]
I'm usually not a big fan of custom scrollbars, it's pretty tough to make them feel natural and handle all the edge cases elegantly. Webkit (chrome/safari) let you style the scrollbar pretty easily, the others will follow suite eventually. I'd recommend just sticking with stock scrolling unless you have specific use-cases or a lot of time on your hands to tune whatever 3rd party solution you like.

**Comment by z4711** [comment]
most of the custom scroll bars are dealing with css, the styling, .... but
all of them related to a div, ul or what else... in fact only cosmetics

due to the way i've done virtual scrolling, my scrollbar doesn't represent
the actual overall position
what im looking for, is a way to handle the "big scroll", the portion
showed (displayItems) relative to items

a virtual scrollbar should take NumItems, Pos as properties, emitting some
events (newPos) when scrolling
so i can fire my goto, something in this direction

2014-10-21 8:06 GMT+02:00 Baz notifications@github.com:

**Comment by thinkloop** [comment]
This is a tough problem to solve. One of the main challenges with infinite scroll is making the scrollbars behave as expected. You would be surprised at how many subtleties are involved in making scrollbars work naturally and nice - which is probably one reason why you don't see too many custom scrollers around. I think people generally like their native scrollers.

I solved the problem by filling up the space outside of view with empty "dummy" containers, so that the scrollbar can adjust accordingly. You could achieve the same with a single large container that changes height as more or less items are represented (I think that's how twitter does it). I'd be cautious trying to roll your own scrolling from scratch.

**Comment by thinkloop** [comment]
To get infinite scrolling to work with variable height items, I think the individual heights of each item must be kept track of, so that once they are out of view, whatever mechanism you are using to manage the out-of-view-space can adjust accordingly (and vice-versa when the item comes back into view).

**Comment by z4711** [comment]
may be a vertical HTML5 <input type=range>

i tried the following site with different browser (Chrome, IE, FF):
http://www.wufoo.com/html5/types/8-range.html
the vertical one is not showed correctly by IE 11 and FF

other ressources:
http://stackoverflow.com/questions/15935837/how-to-display-a-range-input-slider-vertically
http://jsfiddle.net/ArondeParon/SPjsf/15/

i'm not very encouraged to follow this way

2014-10-21 10:12 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by z4711** [comment]
your are completely right...

my version 'ko-scroll-docstruct-maintained' does exactly that (as
knockout-js-infinite-scroll too)
but please try this sample and type go to: 9999 -> not very nice.

i would say for 2-3 thousand entries it will be ok, but above that we
should only render what's visible (no empty containers), like
'ko-scroll-pure-virtual' does.

2014-10-21 11:06 GMT+02:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by thinkloop** [comment]
Can you send the full link again.

**Comment by z4711** [comment]
sorry the samples where sent as attachment...

ko-scroll-docstruct-maintained: http://jsfiddle.net/z4711/r6tg1116/

ko-scroll-pure-virtual: http://jsfiddle.net/z4711/Lae39vx6/1/

2014-10-21 11:41 GMT+02:00 Baz notifications@github.com:

> Can you send the full link again.
>

**Comment by thinkloop** [comment]
Wow those look great! It doesn't seem like they have any problems?

**Comment by z4711** [comment]
but there are problems:

in the http://jsfiddle.net/z4711/r6tg1116/ type 9999 in the goto field,
then wait...

in the http://jsfiddle.net/z4711/Lae39vx6/
http://jsfiddle.net/z4711/Lae39vx6/1/ the document structure is not
maintained, so the scrollbar doesn't reflect the relative position

but anyway, thanks for your appreciation

2014-10-25 16:48 GMT+02:00 Baz notifications@github.com:

**Comment by thinkloop** [comment]
The [second one's](http://jsfiddle.net/z4711/Lae39vx6/) pretty cool! Reverse infinite scroll :) Have you considered making the div height on load tall enough to contain all elements so that the scrollbar proportions are right, then when the user scrolls or clicks on it, you invoke your goto functionality?

**Comment by z4711** [comment]
that's the problem!
in the fiddle the things are simplified, the preceding div heights could be
calculated, but in a real application the div heights will be determined by
its contents, so we would need to render them to know about, on large lists
this will not be applicable.

On my real app (http://84.226.142.49/stm) the viewport will also change
frequently.I often use full screen (desktop) to select musics, for playing
i reduce the window size to something like a phone. I easily create
playlists containing 10000 or more songs, after a while of playing, opening
the playlist again (the sound doesn't stop when the playlist view is
closed), i want to move (goto) directly to the song currently playing of
course. It's true, it will take days to advance a playlist to some thousand
items, but it should be possible.

How to make correct proportions of the scroll bar? the truth is, i don't
have any idea, for the moment...

2014-10-26 2:05 GMT+02:00 Baz notifications@github.com:

**Comment by thinkloop** [comment]
I think there is no option here but to estimate. If the user has scrolled through some items, then you can know and record their exact heights for later, but if the user wants to skip through thousands of items without seeing them, the only performant way to do that without rendering them all is to simply estimate an average height. It won't be exact, but the scrollbar would be so thin at that point, it wouldn't matter if it was a millimeter lower or higher. Perhaps the strategy is:
1. Determine avg item height
2. On page load, load 1 huge div that's as tall as the avg height \* numItems (aka 100px \* 10,000)
   - that way the scrollbar will have the correct approximate proportions
3. As different items are rendered, remember their heights and adjust the background div height accordingly

**Comment by z4711** [comment]
"background div" we will give it a try,
how to implement a background div? do you have done that already? can you
fork my sample to do that?

i already calculated the totalHeight in pixels for my last sample (
http://jsfiddle.net/z4711/Lae39vx6/)

best Peter

2014-10-26 20:25 GMT+01:00 Baz notifications@github.com:

**Comment by thinkloop** [comment]
I never tried an implementation like that, so there may be issues that I am not foreseeing. But say you know you are going to load 1000 items, and the approximate height of each item is 10px, if you load a page with nothing else than 1 div of 10,000px tall, you will have a page with a scrollbar with the right proportions that works properly for that many items. The next step would then be to show the correct items at a given scroll position. So on initial page load, after loading the biig div, you would show the first items as well. When the user clicks somewhere on the scrollbar, especially low in the recordset, you use your efficient goto to render the right items.

I'm oversimplifying of course, but this could be a workable strategy!

**Comment by z4711** [comment]
ok, i did it...

ko-virtual-scroll http://jsfiddle.net/z4711/0x8b760o/:
http://jsfiddle.net/z4711/0x8b760o/
it works fine with Firefox and Chrome, with IE 11 there are some problems
with scrollHeight, open the console to inspect the values scrollPos and
scrollHeight at runtime. Microsoft seems to recalculate for zooming or some
stuff like this.

if there is someone with a good knowledge, please refine it to make it
usable on all browsers

Best Peter

2014-10-27 17:11 GMT+01:00 Baz notifications@github.com:

**Comment by z4711** [comment]
Hi Baz
there is an update version, working with all major browsers now
the problem was that we can't render item heights as we want (the widely
discussed IE8 1342177 pixels problem).

ko-virtual-scoll: http://jsfiddle.net/z4711/gk30zLs2/

regards Peter

2014-10-29 15:55 GMT+01:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by thinkloop** [comment]
This looks great! I didn't read all the code, but the functionality is perfect. You should consider generalizing it and sharing it in a public repo. Nicely done Peter!

**Comment by z4711** [comment]
the real life is a bit harder...

goto http://84.226.142.49/stm#bgcat/512/1038821385 and select all of
Al Di Meola
Chick Corea
Dave Matthews

then you should have 2679 tracks in 220 albums in the playlist

due to heavy contents rendered by Knockout, unfortunately scrolling is not
as fluid as desired
thanks for the recognition
best Peter

2014-11-12 2:37 GMT+01:00 Baz notifications@github.com:

**Comment by z4711** [comment]
generalizing, i will let up to you... (ha ha)

yes it should be possible, unfortunately we depend of some conventions
list must have an id ('itemsUl')
every entry must be identified too (class="sct-target" id='txxx')

view must be something like:
 <div id="itemsUL">
        <div data-bind="style: { height: $root.precedingHeight() + 'px'
}"></div>
        
        <div class="sct-target" data-bind="attr: { id: 't' +
($root.firstRenderedIndex() + $index()) }">
            <div>
                item contents
            </div>
        </div>
        
        <div data-bind="style: { height: $root.trailingHeight() + 'px'
}"></div>
</div>

ok, instead of div we could also use <ul>, <li> or a table...
but all together not the best conditions to create a component

best Peter

2014-11-12 9:37 GMT+01:00 Peter Zehnder peter.zehnder.ibi@gmx.net:

**Comment by ardalis** [comment]
I'm trying to implement ko-infinite-scroll in a client's application that is pretty simple, but require variable height. I don't need to be able to jump to a row without having first rendered previous rows. Basically they want to page through rows about 30 at a time, but each row will be 1-3 rows of text (one row of text is 31px, two is 51px, three is 71px). I can't predict for a given page of 30 whether they will be all single-text-row or what the mix will be, so trying to use an average won't work. Is there a fairly straightforward way to update the code to support this variability? Currently I'm forcing all rows to be 71px, which works correctly but results in a lot of wasted whitespace.  Thanks!
